// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using projectapi.DataModels;

namespace projectapi.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220731093339_nwaa")]
    partial class nwaa
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("projectapi.DataModels.DocumentDetails", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aadhar_Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Collateral")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LOA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NOC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PAN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pay_Slip")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reg_Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Voter_ID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("DocumentDetails");
                });

            modelBuilder.Entity("projectapi.DataModels.IncomeDetails", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Current_Salary")
                        .HasColumnType("bigint");

                    b.Property<string>("Emp_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Employer_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Estimated_Cost")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Occupation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prop_Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Property_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Retirement_Age")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("IncomeDetails");
                });

            modelBuilder.Entity("projectapi.DataModels.LoanDetails", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Amount_Required")
                        .HasColumnType("bigint");

                    b.Property<int>("Elgible_Amount")
                        .HasColumnType("int");

                    b.Property<int>("No_of_installments")
                        .HasColumnType("int");

                    b.Property<int>("ROI")
                        .HasColumnType("int");

                    b.Property<long>("Reference_Number")
                        .HasColumnType("bigint");

                    b.Property<int>("Tenure_of_payment")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("LoanDetails");
                });

            modelBuilder.Entity("projectapi.DataModels.UserAccountTable", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Account_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Signature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_At")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserLoanID")
                        .HasColumnType("int");

                    b.Property<int?>("UserTableID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UserLoanID");

                    b.HasIndex("UserTableID");

                    b.ToTable("UserAccountTable");
                });

            modelBuilder.Entity("projectapi.DataModels.UserBankDetails", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Account_Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bank_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IFSC")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("UserBankDetails");
                });

            modelBuilder.Entity("projectapi.DataModels.UserLoan", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date_Sanctioned")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DocumentDetailsID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Due_Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IncomeDetailsID")
                        .HasColumnType("int");

                    b.Property<int?>("LoanDetailsID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Next_Due_Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Remaining_Amount")
                        .HasColumnType("int");

                    b.Property<int?>("UserBankID")
                        .HasColumnType("int");

                    b.Property<int?>("UserDetailsID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("DocumentDetailsID");

                    b.HasIndex("IncomeDetailsID");

                    b.HasIndex("LoanDetailsID");

                    b.HasIndex("UserBankID");

                    b.HasIndex("UserDetailsID");

                    b.ToTable("UserLoan");
                });

            modelBuilder.Entity("projectapi.DataModels.UserTable", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("Emai_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("First_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Last_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Middle_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Phone_Number")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.ToTable("UserTable");
                });

            modelBuilder.Entity("projectapi.DataModels.UserAccountTable", b =>
                {
                    b.HasOne("projectapi.DataModels.UserLoan", "UserLoan")
                        .WithMany()
                        .HasForeignKey("UserLoanID");

                    b.HasOne("projectapi.DataModels.UserTable", "UserTable")
                        .WithMany()
                        .HasForeignKey("UserTableID");

                    b.Navigation("UserLoan");

                    b.Navigation("UserTable");
                });

            modelBuilder.Entity("projectapi.DataModels.UserLoan", b =>
                {
                    b.HasOne("projectapi.DataModels.DocumentDetails", "DocumentDetails")
                        .WithMany()
                        .HasForeignKey("DocumentDetailsID");

                    b.HasOne("projectapi.DataModels.IncomeDetails", "IncomeDetails")
                        .WithMany()
                        .HasForeignKey("IncomeDetailsID");

                    b.HasOne("projectapi.DataModels.LoanDetails", "LoanDetails")
                        .WithMany()
                        .HasForeignKey("LoanDetailsID");

                    b.HasOne("projectapi.DataModels.UserBankDetails", "UserBank")
                        .WithMany()
                        .HasForeignKey("UserBankID");

                    b.HasOne("projectapi.DataModels.UserTable", "UserDetails")
                        .WithMany()
                        .HasForeignKey("UserDetailsID");

                    b.Navigation("DocumentDetails");

                    b.Navigation("IncomeDetails");

                    b.Navigation("LoanDetails");

                    b.Navigation("UserBank");

                    b.Navigation("UserDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
