// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using projectapi.DataModels;

namespace projectapi.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("projectapi.DataModels.DocumentDetails", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aadhar_Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Collateral")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LOA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NOC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reg_Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("panId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("salarySlip")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("saleAgreement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("voterId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("DocumentDetails");
                });

            modelBuilder.Entity("projectapi.DataModels.IncomeDetails", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Current_Sallary")
                        .HasColumnType("bigint");

                    b.Property<string>("Employer_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Occupation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employmentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("estimatedCost")
                        .HasColumnType("bigint");

                    b.Property<string>("propertyLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("propertyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("retire")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("IncomeDetails");
                });

            modelBuilder.Entity("projectapi.DataModels.LoanDetails", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Amount_Required")
                        .HasColumnType("bigint");

                    b.Property<int>("Elgible_Amount")
                        .HasColumnType("int");

                    b.Property<int>("No_of_installments")
                        .HasColumnType("int");

                    b.Property<int>("ROI")
                        .HasColumnType("int");

                    b.Property<long>("Reference_Number")
                        .HasColumnType("bigint");

                    b.Property<long>("loanAmount")
                        .HasColumnType("bigint");

                    b.Property<string>("tenure")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("LoanDetails");
                });

            modelBuilder.Entity("projectapi.DataModels.UserAccountTable", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Account_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Signature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_At")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserLoanID")
                        .HasColumnType("int");

                    b.Property<int?>("UserTableId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UserLoanID");

                    b.HasIndex("UserTableId");

                    b.ToTable("UserAccountTable");
                });

            modelBuilder.Entity("projectapi.DataModels.UserBankDetails", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Account_Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bank_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IFSC")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("UserBankDetails");
                });

            modelBuilder.Entity("projectapi.DataModels.UserLoan", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date_Sanctioned")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DocumentDetailsID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Due_Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IncomeDetailsID")
                        .HasColumnType("int");

                    b.Property<int?>("LoanDetailsID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Next_Due_Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Remaining_Amount")
                        .HasColumnType("int");

                    b.Property<int?>("UserBankID")
                        .HasColumnType("int");

                    b.Property<int?>("UserDetailsId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("DocumentDetailsID");

                    b.HasIndex("IncomeDetailsID");

                    b.HasIndex("LoanDetailsID");

                    b.HasIndex("UserBankID");

                    b.HasIndex("UserDetailsId");

                    b.ToTable("UserLoan");
                });

            modelBuilder.Entity("projectapi.DataModels.UserTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("adharNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("emailId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("middleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nationality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("panId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("phNumber")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("UserTable");
                });

            modelBuilder.Entity("projectapi.DataModels.UserAccountTable", b =>
                {
                    b.HasOne("projectapi.DataModels.UserLoan", "UserLoan")
                        .WithMany()
                        .HasForeignKey("UserLoanID");

                    b.HasOne("projectapi.DataModels.UserTable", "UserTable")
                        .WithMany()
                        .HasForeignKey("UserTableId");

                    b.Navigation("UserLoan");

                    b.Navigation("UserTable");
                });

            modelBuilder.Entity("projectapi.DataModels.UserLoan", b =>
                {
                    b.HasOne("projectapi.DataModels.DocumentDetails", "DocumentDetails")
                        .WithMany()
                        .HasForeignKey("DocumentDetailsID");

                    b.HasOne("projectapi.DataModels.IncomeDetails", "IncomeDetails")
                        .WithMany()
                        .HasForeignKey("IncomeDetailsID");

                    b.HasOne("projectapi.DataModels.LoanDetails", "LoanDetails")
                        .WithMany()
                        .HasForeignKey("LoanDetailsID");

                    b.HasOne("projectapi.DataModels.UserBankDetails", "UserBank")
                        .WithMany()
                        .HasForeignKey("UserBankID");

                    b.HasOne("projectapi.DataModels.UserTable", "UserDetails")
                        .WithMany()
                        .HasForeignKey("UserDetailsId");

                    b.Navigation("DocumentDetails");

                    b.Navigation("IncomeDetails");

                    b.Navigation("LoanDetails");

                    b.Navigation("UserBank");

                    b.Navigation("UserDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
